# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 919b2d1152595ce6450fa35fabcf2a026220dc6693fafc1cbaeff81020cd81ad0e381a752c834dc0ec0a1a8e84c21fd944e68d63adfa9e54a0e83ad83520f601

test:
  secret_key_base: dbf09d362fc015f676e1c2306a834909e167b3b5ee078d59fca90035d2b1e1ce7a52d0d4f54761c83d11809024fae34c1cb65e6cfbd7c9258a935ac8be92b008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
